### ISSUE TITLE
Rewrite in Vyper?

### ISSUE THREAD

**Issue by shazow** [vipnode/vipnode-contract#3]
No great reason, but could be fun and simplify the code.

**Comment by Solexplorer** [comment]
@shazow I can do it if you want

**Comment by shazow** [comment]
@Solexplorer Hiya, thanks for the offer! I'd certainly merge the contribution, at least as a reference alongside of the existing contract.

We're not leaning heavily on the contract-based payment system for Vipnode at the moment, so it's not super important.

**Comment by Solexplorer** [comment]
@shazow Created a pull request for the contract

**Comment by shazow** [comment]
Thanks very much!
